AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
